steps:
    # Install npm dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    # Build polymer application
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
    # Build Docker container
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/shopRun:$REVISION_ID', './']
    # Push container to gcr.io repo
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/$PROJECT_ID/shopRun"]
    # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'shop', '--image', 'gcr.io/$PROJECT_ID/shopRun:$REVISION_ID', '--region', 'us-central1', '--platform', 'managed']