steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://source.developers.google.com/p/gcp-demos-229619/r/cloudrundemo']
  # Install npm dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  # Build polymer application
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  # Build Docker container
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloudrun-demo:$REVISION_ID', './server']
  # Push container to gcr.io repo
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/cloudrun-demo"]
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'cloudrun-demo', '--image', 'gcr.io/$PROJECT_ID/cloudrun-demo:$REVISION_ID', '--region', 'us-central1', '--platform', 'managed']
