steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/Polymer/shop.git']
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloudrun-demo:${SHORT_SHA}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/cloudrun-demo"]
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'cloudrun-demo', '--image', 'gcr.io/$PROJECT_ID/cloudrun-demo', '--region', 'us-central1', '--platform', 'managed']
images:
- gcr.io/$PROJECT_ID/cloudrun-demo
